<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
        <CETCompat>false</CETCompat>
        <Version>0.4.0</Version>
        <Copyright>Copyright © NotScuffed 2025</Copyright>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DebugType>none</DebugType>
    </PropertyGroup>
</Project>
