//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePKG.Neo.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang___复制 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang___复制() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RePKG.Neo.Resources.Lang - 复制", typeof(Lang___复制).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copy project.json and preview.jpg from beside PKG into output directory 的本地化字符串。
        /// </summary>
        public static string Main_Copy {
            get {
                return ResourceManager.GetString("Main_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract 的本地化字符串。
        /// </summary>
        public static string Main_Extract {
            get {
                return ResourceManager.GetString("Main_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input File (.pkg/.tex): 的本地化字符串。
        /// </summary>
        public static string Main_InputFile {
            get {
                return ResourceManager.GetString("Main_InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t convert TEX files into images while extracting PKG 的本地化字符串。
        /// </summary>
        public static string Main_NoCvt {
            get {
                return ResourceManager.GetString("Main_NoCvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Main_Open {
            get {
                return ResourceManager.GetString("Main_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Directory: 的本地化字符串。
        /// </summary>
        public static string Main_OutputDir {
            get {
                return ResourceManager.GetString("Main_OutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Main_Select {
            get {
                return ResourceManager.GetString("Main_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip: You can drop a file / folder here. 的本地化字符串。
        /// </summary>
        public static string Main_Tip {
            get {
                return ResourceManager.GetString("Main_Tip", resourceCulture);
            }
        }
    }
}
