//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePKG.Neo.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RePKG.Neo.res.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string Btn_AddFile {
            get {
                return ResourceManager.GetString("Btn_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string Btn_AddFolder {
            get {
                return ResourceManager.GetString("Btn_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursively search supported files (.pkg, .mpkg, .tex).
        /// </summary>
        public static string Btn_AddFolder_ToolTip {
            get {
                return ResourceManager.GetString("Btn_AddFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Btn_Clear_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Clear_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Btn_Options {
            get {
                return ResourceManager.GetString("Btn_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Btn_Remove_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reveal in File Explorer.
        /// </summary>
        public static string Btn_Reveal_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Reveal_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string Btn_StartExtract {
            get {
                return ResourceManager.GetString("Btn_StartExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Btn_Stop_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Stop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log.
        /// </summary>
        public static string Btn_ViewLog {
            get {
                return ResourceManager.GetString("Btn_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start extraction.
        /// </summary>
        public static string Chk_AutoExtract {
            get {
                return ResourceManager.GetString("Chk_AutoExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy project.json and preview.jpg to output directory.
        /// </summary>
        public static string Chk_CopyProject {
            get {
                return ResourceManager.GetString("Chk_CopyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save TEX files.
        /// </summary>
        public static string Chk_NoRawTex {
            get {
                return ResourceManager.GetString("Chk_NoRawTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t convert TEX to images.
        /// </summary>
        public static string Chk_NoTexConvert {
            get {
                return ResourceManager.GetString("Chk_NoTexConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put all output files in single directory.
        /// </summary>
        public static string Chk_SingleDir {
            get {
                return ResourceManager.GetString("Chk_SingleDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag files / folders here.
        /// </summary>
        public static string EmptyState_Text {
            get {
                return ResourceManager.GetString("EmptyState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string FolderDialog_Title {
            get {
                return ResourceManager.GetString("FolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Item_Complete {
            get {
                return ResourceManager.GetString("Item_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed.
        /// </summary>
        public static string Item_ExtractFailed {
            get {
                return ResourceManager.GetString("Item_ExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string Item_FileNotFound {
            get {
                return ResourceManager.GetString("Item_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string Item_Handling {
            get {
                return ResourceManager.GetString("Item_Handling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output dir suffix.
        /// </summary>
        public static string Lbl_OutputSuffix {
            get {
                return ResourceManager.GetString("Lbl_OutputSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Msg_Confirm {
            get {
                return ResourceManager.GetString("Msg_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please drop after current tasks are completed..
        /// </summary>
        public static string Msg_DropWhenRunning {
            get {
                return ResourceManager.GetString("Msg_DropWhenRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_Error {
            get {
                return ResourceManager.GetString("Msg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred when starting up RePKG.Neo. Some functions (e.g. log, config) may be unavailable..
        /// </summary>
        public static string Msg_ErrorStartUp {
            get {
                return ResourceManager.GetString("Msg_ErrorStartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during extraction:
        ///
        ///{0}
        ///
        ///Please check if the input file is valid..
        /// </summary>
        public static string Msg_ExtractError {
            get {
                return ResourceManager.GetString("Msg_ExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed.
        /// </summary>
        public static string Msg_ExtractFailed_Title {
            get {
                return ResourceManager.GetString("Msg_ExtractFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to re-extract the succeeded items?.
        /// </summary>
        public static string Msg_ExtractSucceeded {
            get {
                return ResourceManager.GetString("Msg_ExtractSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RePKG.Neo is exiting due to a fatal error. Click &quot;Yes&quot; to open log for details..
        /// </summary>
        public static string Msg_FatalError {
            get {
                return ResourceManager.GetString("Msg_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKG File|*.pkg|MPKG File|*.mpkg|TEX File|*.tex|All Files|*.*.
        /// </summary>
        public static string Msg_FileFilter {
            get {
                return ResourceManager.GetString("Msg_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Msg_Info {
            get {
                return ResourceManager.GetString("Msg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid drop. Please drag a file or folder..
        /// </summary>
        public static string Msg_InvalidDrop {
            get {
                return ResourceManager.GetString("Msg_InvalidDrop", resourceCulture);
            }
        }
    }
}
