//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePKG.Neo.res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RePKG.Neo.res.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add file 的本地化字符串。
        /// </summary>
        public static string Btn_AddFile {
            get {
                return ResourceManager.GetString("Btn_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add folder 的本地化字符串。
        /// </summary>
        public static string Btn_AddFolder {
            get {
                return ResourceManager.GetString("Btn_AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recursively search supported files (.pkg, .mpkg, .tex) 的本地化字符串。
        /// </summary>
        public static string Btn_AddFolder_ToolTip {
            get {
                return ResourceManager.GetString("Btn_AddFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Btn_Clear_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Clear_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Btn_Options {
            get {
                return ResourceManager.GetString("Btn_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Btn_Remove_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reveal in File Explorer 的本地化字符串。
        /// </summary>
        public static string Btn_Reveal_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Reveal_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract 的本地化字符串。
        /// </summary>
        public static string Btn_StartExtract {
            get {
                return ResourceManager.GetString("Btn_StartExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Btn_Stop_ToolTip {
            get {
                return ResourceManager.GetString("Btn_Stop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto start extraction 的本地化字符串。
        /// </summary>
        public static string Chk_AutoExtract {
            get {
                return ResourceManager.GetString("Chk_AutoExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy project.json and preview.jpg to output directory 的本地化字符串。
        /// </summary>
        public static string Chk_CopyProject {
            get {
                return ResourceManager.GetString("Chk_CopyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t save TEX files 的本地化字符串。
        /// </summary>
        public static string Chk_NoRawTex {
            get {
                return ResourceManager.GetString("Chk_NoRawTex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t convert TEX to images 的本地化字符串。
        /// </summary>
        public static string Chk_NoTexConvert {
            get {
                return ResourceManager.GetString("Chk_NoTexConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Put all output files in single directory 的本地化字符串。
        /// </summary>
        public static string Chk_SingleDir {
            get {
                return ResourceManager.GetString("Chk_SingleDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag files / folders here 的本地化字符串。
        /// </summary>
        public static string EmptyState_Text {
            get {
                return ResourceManager.GetString("EmptyState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add folder 的本地化字符串。
        /// </summary>
        public static string FolderDialog_Title {
            get {
                return ResourceManager.GetString("FolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        public static string Item_Complete {
            get {
                return ResourceManager.GetString("Item_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extraction failed 的本地化字符串。
        /// </summary>
        public static string Item_ExtractFailed {
            get {
                return ResourceManager.GetString("Item_ExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found 的本地化字符串。
        /// </summary>
        public static string Item_FileNotFound {
            get {
                return ResourceManager.GetString("Item_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output dir suffix 的本地化字符串。
        /// </summary>
        public static string Lbl_OutputSuffix {
            get {
                return ResourceManager.GetString("Lbl_OutputSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please drop after current tasks are completed. 的本地化字符串。
        /// </summary>
        public static string Msg_DropWhenRunning {
            get {
                return ResourceManager.GetString("Msg_DropWhenRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during extraction:
        ///
        ///{0}
        ///
        ///Please check if the input file is valid. 的本地化字符串。
        /// </summary>
        public static string Msg_ExtractError {
            get {
                return ResourceManager.GetString("Msg_ExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extraction failed 的本地化字符串。
        /// </summary>
        public static string Msg_ExtractFailed_Title {
            get {
                return ResourceManager.GetString("Msg_ExtractFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PKG File|*.pkg|MPKG File|*.mpkg|TEX File|*.tex|All Files|*.* 的本地化字符串。
        /// </summary>
        public static string Msg_FileFilter {
            get {
                return ResourceManager.GetString("Msg_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Msg_Info {
            get {
                return ResourceManager.GetString("Msg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid drop. Please drag a file or folder. 的本地化字符串。
        /// </summary>
        public static string Msg_InvalidDrop {
            get {
                return ResourceManager.GetString("Msg_InvalidDrop", resourceCulture);
            }
        }
    }
}
